#!/bin/bash
#Schetchiki dostupnosti hostov
available=0
unavailable=0
# host's
arr=(mail.ru yandex.ru)

# Just elements.
for element in "${arr[@]}"; do
    ping -c 1 -s 1 -W 1 $element >/dev/null 2>&1 && { echo "Хост [$element] доступен"; available=$(( available + 1 )); } || { echo "Хост [$element] недоступен"; unavailable=$(( unavailable + 1 )); }
done

echo "Kоличество доступных машин: $available"
echo "Kоличество недоступных машин: $unavailable"
